export type ItemCategory = "electronics" | "furniture" | "clothing" | "collectibles" | "tools" | "misc" | "vehicle" | "property";

export type ItemTemplate = {
    name: string;
    description: string;
    category: ItemCategory;
    internalValue: number;
};

export const ITEM_TEMPLATES: ItemTemplate[] = [
    // Electronics
    { name: "Broken Laptop", description: "Boots to Philosophy", category: "electronics", internalValue: 45 },
    { name: "Old CRT Monitor", description: "Weighs More Than Regrets", category: "electronics", internalValue: 30 },
    { name: "Vintage Radio", description: "Picks Up One Station", category: "electronics", internalValue: 65 },
    { name: "Tangled Headphones", description: "Knot Included", category: "electronics", internalValue: 12 },
    { name: "Cracked Tablet", description: "Abstract Screen Art", category: "electronics", internalValue: 38 },
    { name: "Digital Camera", description: "No Charger", category: "electronics", internalValue: 55 },
    { name: "Old Gaming Console", description: "Cartridge Not Included", category: "electronics", internalValue: 80 },
    { name: "Wireless Keyboard", description: "Battery Unknown", category: "electronics", internalValue: 18 },
    { name: "Mini Fridge", description: "With Personality", category: "electronics", internalValue: 600 },
    { name: "Antenna Array", description: "For Listening to Memories", category: "electronics", internalValue: 7500 },
    { name: "Artisan Toaster", description: "Charms Guests", category: "electronics", internalValue: 9000 },

    // Furniture
    { name: "Wobbly Bar Stool", description: "Character Build", category: "furniture", internalValue: 20 },
    { name: "Scratched Coffee Table", description: "Naturally Distressed", category: "furniture", internalValue: 35 },
    { name: "Fold-out Lawn Chair", description: "Folds Back Unexpectedly", category: "furniture", internalValue: 14 },
    { name: "Vintage Lamp", description: "Illuminates Poorly, Stylishly", category: "furniture", internalValue: 50 },
    { name: "Bookshelf", description: "Missing Shelf", category: "furniture", internalValue: 25 },
    { name: "Rocking Chair", description: "Makes Spooky Noises", category: "furniture", internalValue: 60 },
    { name: "Porch Swing", description: "Needs Love", category: "furniture", internalValue: 400 },
    { name: "Shag Rug", description: "1970s, Very Proud", category: "furniture", internalValue: 2600 },
    { name: "Garage Sale Lamp", description: "Ambient, Old", category: "furniture", internalValue: 4200 },
    { name: "Comfy Recliner", description: "Has Stories", category: "furniture", internalValue: 5000 },
    { name: "Glass Chandelier", description: "Dusty, Dramatic", category: "furniture", internalValue: 55000 },
    { name: "Gilded Mirror", description: "Reflects Opinions", category: "furniture", internalValue: 97000 },
    { name: "Antique Bathtub", description: "Clawfoot Majesty", category: "furniture", internalValue: 142000 },
    { name: "Library Ladder", description: "Sliding, Regal", category: "furniture", internalValue: 3200 },

    // Clothing
    { name: "Leather Jacket", description: "Worn", category: "clothing", internalValue: 40 },
    { name: "Vintage Band Tee", description: "Band Unverifiable", category: "clothing", internalValue: 22 },
    { name: "Cowboy Boots", description: "No Cowboys Included", category: "clothing", internalValue: 55 },
    { name: "Fur Coat", description: "Faux", category: "clothing", internalValue: 30 },
    { name: "Denim Overalls", description: "Farmer Optional", category: "clothing", internalValue: 18 },
    { name: "Assorted Mismatched Socks", description: "Rare Pair Inside", category: "clothing", internalValue: 800 },
    { name: "Pair of Sneakers with Personality", description: "Smells Like It", category: "clothing", internalValue: 38000 },

    // Collectibles
    { name: "Baseball Card", description: "Unknown Player", category: "collectibles", internalValue: 15 },
    { name: "Porcelain Figurine", description: "Deeply Judgmental", category: "collectibles", internalValue: 45 },
    { name: "Old Comic Book", description: "Missing Last Page", category: "collectibles", internalValue: 35 },
    { name: "Coin Collection", description: "Partial", category: "collectibles", internalValue: 70 },
    { name: "Signed Poster", description: "Unverified", category: "collectibles", internalValue: 28 },
    { name: "Snow Globe", description: "Snow Goes Sideways", category: "collectibles", internalValue: 12 },
    { name: "Vintage Lunchbox", description: "Thermos Long Gone", category: "collectibles", internalValue: 40 },
    { name: "Handwritten Map to Nowhere", description: "Confident Penmanship", category: "collectibles", internalValue: 52000 },
    { name: "Speedboat Model", description: "Scale: Imagination", category: "collectibles", internalValue: 6200 },
    { name: "Ceramic Cat with Mysterious Eyes", description: "Watches You Sleep", category: "collectibles", internalValue: 11000 },
    { name: "Vinyl Record Collection", description: "Mostly Hits", category: "collectibles", internalValue: 66000 },
    { name: "Carousel Horse", description: "Retired Performer", category: "collectibles", internalValue: 83000 },
    { name: "Retro Diner Sign", description: "Neon Flicker", category: "collectibles", internalValue: 860000 },
    { name: "Porch Bell Tower", description: "Miniature", category: "collectibles", internalValue: 125000 },
    { name: "Pool Table with Character", description: "Two Balls Missing", category: "collectibles", internalValue: 215000 },

    // Tools
    { name: "Rusty Hand Saw", description: "Adds Ambiance", category: "tools", internalValue: 10 },
    { name: "Power Drill", description: "No Bits", category: "tools", internalValue: 32 },
    { name: "Toolbox", description: "Half Empty", category: "tools", internalValue: 28 },
    { name: "Vintage Pocket Knife", description: "Blade Stiff, Opinions Firm", category: "tools", internalValue: 48 },
    { name: "Level Tool Set", description: "Neither, Actually", category: "tools", internalValue: 20 },
    { name: "Handcarved Canoe Paddle", description: "Signed?", category: "tools", internalValue: 46000 },
    { name: "Pedal-Powered Lawnmower", description: "Vintage Fitness", category: "tools", internalValue: 79000 },

    // Misc
    { name: "Box of Old VHS Tapes", description: "Be Kind, Rewind", category: "misc", internalValue: 8 },
    { name: "Jigsaw Puzzle", description: "Possibly Incomplete", category: "misc", internalValue: 5 },
    { name: "Framed Painting", description: "Unknown Artist", category: "misc", internalValue: 55 },
    { name: "Typewriter", description: "Delete Key Missing", category: "misc", internalValue: 90 },
    { name: "Vintage Sewing Machine", description: "Thread Sold Separately", category: "misc", internalValue: 75 },
    { name: "Rotary Phone", description: "Infinite Hold Music", category: "misc", internalValue: 42 },
    { name: "Bag of Miscellaneous Cables", description: "None Match Anything", category: "misc", internalValue: 3 },
    { name: "Hand-Painted Yard Gnome", description: "Sassy", category: "misc", internalValue: 100 },
    { name: "Mystery Box", description: "Probably Screws", category: "misc", internalValue: 150 },
    { name: "Roadside Snowman", description: "Melted Interior", category: "misc", internalValue: 200 },
    { name: "Squeaky Doorbell Collection", description: "Fully Operational, Barely", category: "misc", internalValue: 250 },
    { name: "Assorted Rubber Duckies", description: "Emotional Support", category: "misc", internalValue: 300 },
    { name: "Limited Edition Coffee Can", description: "Carried for Decades", category: "misc", internalValue: 350 },
    { name: "Box of Unreadable VHS Labels", description: "Probably Movies", category: "misc", internalValue: 450 },
    { name: "Wobbly Wagon", description: "Two Wheels, Big Dreams", category: "misc", internalValue: 500 },
    { name: "Polished Doorknob", description: "Slightly Regal", category: "misc", internalValue: 1200 },
    { name: "Bubble-Wrapped Mystery", description: "Do Not Pop", category: "misc", internalValue: 1400 },
    { name: "Lawn Gnome Family", description: "Extended Warranty Void", category: "misc", internalValue: 1600 },
    { name: "Casserole Dish", description: "Cousin's Secret Recipe", category: "misc", internalValue: 1800 },
    { name: "Hand-Knitted Blanket", description: "Pet Approved", category: "misc", internalValue: 2000 },
    { name: "Retro Clock", description: "Ticks Dramatically", category: "misc", internalValue: 3000 },
    { name: "Antique Trunk", description: "Holds Regrets", category: "misc", internalValue: 13000 },
    { name: "Mailbox from Another Era", description: "Still Hopeful", category: "misc", internalValue: 2500 },
    { name: "Wind-Up Clockwork Bird", description: "Sings Once, Dramatically", category: "misc", internalValue: 20000 },
    { name: "Set of Elegant Plates", description: "Elegant Chip", category: "misc", internalValue: 25000 },
    { name: "Boxcar Full of Yesterday", description: "No Return Address", category: "misc", internalValue: 68000 },
    { name: "Decorative Garden Flamingo", description: "Wings Missing", category: "misc", internalValue: 700 },
    { name: "Porch Piano", description: "Out of Tune, Expressive", category: "misc", internalValue: 31000 },

    // Vehicles
    { name: "Vintage Scooter", description: "One Good Wheel", category: "vehicle", internalValue: 1000 },
    { name: "Bicycle with Inspiring Rust Patterns", description: "Patina, Not Decay", category: "vehicle", internalValue: 2300 },
    { name: "Classic Motorcycle Frame", description: "Dream Project", category: "vehicle", internalValue: 25000 },
    { name: "Dented Delivery Van", description: "Well-Traveled", category: "vehicle", internalValue: 40000 },
    { name: "Pickup Truck with Stories", description: "All Unverified", category: "vehicle", internalValue: 80000 },
    { name: "Convertible that Looks Fast", description: "Standing Still", category: "vehicle", internalValue: 620000 },
    { name: "Classic Sedan", description: "Runs, Sometimes", category: "vehicle", internalValue: 150000 },
    { name: "Food Truck", description: "Dreams Included", category: "vehicle", internalValue: 65000 },
    { name: "Vintage Firetruck", description: "Community Mascot", category: "vehicle", internalValue: 695000 },
    { name: "Classic Station Wagon", description: "Family Heirloom", category: "vehicle", internalValue: 600000 },
    { name: "Runabout Speedboat", description: "Polished Dreams", category: "vehicle", internalValue: 820000 },
    { name: "Diamond-Encrusted Yacht", description: "Chase Item", category: "vehicle", internalValue: 9999999 },
    { name: "Lunar Limo Prototype", description: "Chase Item", category: "vehicle", internalValue: 3333333 },

    // Property
    { name: "Beachfront Timeshare Voucher", description: "Optimistic", category: "property", internalValue: 160000 },
    { name: "Tiny House on Wheels", description: "Lovingly Leaky", category: "property", internalValue: 192000 },
    { name: "Countryside Cottage", description: "Needs TLC", category: "property", internalValue: 230000 },
    { name: "Two-Story Townhouse", description: "Charming Mold", category: "property", internalValue: 275000 },
    { name: "Prefab Cabin", description: "by the Lake", category: "property", internalValue: 425000 },
    { name: "Urban Loft with Industrial Charm", description: "Pipes Very Present", category: "property", internalValue: 485000 },
    { name: "Seaside Bungalow", description: "Salt-Touched", category: "property", internalValue: 950000 },
    { name: "Off-Grid Tiny Farm", description: "Grid Optional", category: "property", internalValue: 380000 },
    { name: "Rooftop Garden Plot", description: "City Views", category: "property", internalValue: 270000 },
    { name: "Underground Bunker", description: "Cache of Socks", category: "property", internalValue: 305000 },
    { name: "Silo Apartment", description: "Now Trendy", category: "property", internalValue: 475000 },
    { name: "Two-Car Garage", description: "With Echoes", category: "property", internalValue: 700000 },
    { name: "Estate-Sized Shed", description: "Ambition Level: High", category: "property", internalValue: 245000 },
    { name: "Greenhouse", description: "Plant Residency Included", category: "property", internalValue: 175000 },
    { name: "Secret Wine Cellar", description: "Mostly Juice", category: "property", internalValue: 240000 },
    { name: "Helipad", description: "Toy Sized", category: "property", internalValue: 2400 },
    { name: "Riverside Gazebo", description: "Romantic, Damp", category: "property", internalValue: 425000 },
    { name: "Haunted Victorian Mansion", description: "Chase Item", category: "property", internalValue: 6666666 },
];
