export type NPCPersona = {
    name: string;
    aggressionSeed: number;
};

export const NPC_PERSONAS: NPCPersona[] = [
    { name: "DealHunter92", aggressionSeed: 0.7 },
    { name: "FlipKing", aggressionSeed: 0.85 },
    { name: "BargainBob", aggressionSeed: 0.4 },
    { name: "ThriftQueen", aggressionSeed: 0.6 },
    { name: "LowballLarry", aggressionSeed: 0.3 },
    { name: "SavvySeller", aggressionSeed: 0.65 },
    { name: "JunkYardJane", aggressionSeed: 0.5 },
    { name: "CurbsideCraig", aggressionSeed: 0.45 },
    { name: "GarageGuru", aggressionSeed: 0.75 },
    { name: "ScrapQueen", aggressionSeed: 0.55 },
    { name: "BinDiver", aggressionSeed: 0.35 },
    { name: "MarketMaven", aggressionSeed: 0.8 },
    { name: "ResaleRaj", aggressionSeed: 0.6 },
    { name: "FlipsterFred", aggressionSeed: 0.7 },
    { name: "WholesaleWendy", aggressionSeed: 0.9 },
    { name: "FlipWizard", aggressionSeed: 0.82 },
    { name: "ThriftMaster", aggressionSeed: 0.58 },
    { name: "PennyPincherPat", aggressionSeed: 0.25 },
    { name: "AuctionAce", aggressionSeed: 0.88 },
    { name: "SalvageSam", aggressionSeed: 0.47 },
    { name: "RustyRita", aggressionSeed: 0.33 },
    { name: "NeonNate", aggressionSeed: 0.6 },
    { name: "ClearanceClara", aggressionSeed: 0.52 },
    { name: "HagglerHank", aggressionSeed: 0.29 },
    { name: "BargainBella", aggressionSeed: 0.61 },
    { name: "ResellRamon", aggressionSeed: 0.73 },
    { name: "ClosetCollector", aggressionSeed: 0.42 },
    { name: "DumpsterDina", aggressionSeed: 0.36 },
    { name: "FleaMarketMoe", aggressionSeed: 0.49 },
    { name: "QuickFlipQuinn", aggressionSeed: 0.77 },
    { name: "ThriftHunterTheo", aggressionSeed: 0.66 },
    { name: "PennywisePete", aggressionSeed: 0.31 },
    { name: "SecondhandSally", aggressionSeed: 0.54 },
    { name: "SalvageSeth", aggressionSeed: 0.44 },
    { name: "PickersPaula", aggressionSeed: 0.39 },
    { name: "MarketMogul", aggressionSeed: 0.92 },
    { name: "AuctionAnna", aggressionSeed: 0.1 },
    { name: "DealDiva", aggressionSeed: 0.68 },
    { name: "FlipFanatic", aggressionSeed: 0.79 },
    { name: "BargainBasil", aggressionSeed: 0.34 },
    { name: "CheapCharlie", aggressionSeed: 0.28 },
    { name: "RetroRoxy", aggressionSeed: 0.56 },
    { name: "NiftyNora", aggressionSeed: 0.5 },
    { name: "GarageGabe", aggressionSeed: 0.46 },
    { name: "TreasureTia", aggressionSeed: 0.63 },
];
